### ISSUE TITLE
Unable to connect with safari (chrome ios)

### ISSUE THREAD

**Issue by thenfour** [thenfour/digifujam#138]

**Comment by lfrancis** [comment]
Doesn't Chrome iOS use webkit rather than Chrome's fork?

**Comment by thenfour** [comment]
Yep it does. And I am reading now that webkit has no implementation of ConstantSourceNode, so unfortunately this is pretty much a deal-breaker unless a workaround is implemented. Totally possible, but also considering Safari doesn't support MIDI, I can't prioritize it at the moment.

https://stackoverflow.com/questions/61377977/web-audio-api-audiocontext-createconstantsource-isnt-implemented-in-safari

**Comment by thenfour** [comment]
basically a dupe of #12
