### ISSUE TITLE
Couldn't hear instrument or tell if connection was successful

### ISSUE THREAD

**Issue by lfrancis** [thenfour/digifujam#139]
Using Chrome-latest on Catalina-latest and as a guest user, I didn't hear the selected instrument, nor could I tell if midi events were getting though. I tried both available interfaces (Akai MPK Mini USB and Mio DIN/USB).

**Comment by thenfour** [comment]
Agree that the current design is not so robust in this regard. The normal workflow is something like:

1. you connect (you know you're connected when you can see the room artwork and list of instruments)
2. hover over an instrument and click "play". you only see this option if you have MIDI devices available to the browser. Your avatar will show the instrument you're currently controlling.
3. If you haven't selected a MIDI device yet, there should be a huge red banner asking you to choose a MIDI device.

After you choose a device, the red banner goes away and you should be able to play. The piano display at the bottom of the screen will show the notes your playing if everything is OK at this point.

But in the case that something goes wrong along the way, it's indeed difficult to tell what happened. Some common things I've seen for example:

- Firefox doesn't support MIDI, and I don't display any warning about this. (not your case, but just wanted to mention)
- Some physical MIDI devices appear as multiple devices, some of which are only used for sysex or other non-performance data. If you happen to choose one of these you won't be able to play.
- There are the occasional bugs; this project is a hobby and it's very new so it's great to report bugs in as much detail as possible :)

as for a general method of introspection / troubleshooting for end users I'm just not there yet. Still busy with feature-building and seeing how the site gets used (if at all!).

**Comment by lfrancis** [comment]
Gotcha on the on-screen kybd providing feedback that the interface is working, makes sense. Tried again with my MIDI interface disconnected so only my MPK USB device would show up, still no love. Same in Edge. Let me know if there's any more info you'd like me to provide.

**Comment by thenfour** [comment]
Hmm I'm not sure what's going on, but a couple ideas for troubleshooting:

- check if other websites work which use MIDI, like multiplayer piano
- check Chrome's dev tools (F12) to see if there are any exceptions happening (another area which is currently not handled gracefully by the current code)
- make sure other apps aren't currently using the device. For example I noticed if I've been recently using a device in my DAW, it won't work on the site.

Beyond that it would take deeper debugging

**Comment by lfrancis** [comment]
Welp, I do use Logic Pro but it's not currently active. I'll restart my machine and see if that releases anything. In the meantime, the Chrome console shows a few things:

The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

DevTools failed to load SourceMap: Could not load content for webpack://digifujam/node_modules/midimessage/dist/dist/index.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

Someone else joined while I had an active session and I could hear their playing around with various sounds, fwiw.

**Comment by lfrancis** [comment]
Ok, after restarting everything works and no errors present in the console. Works even after I start up and then close a Logic session. Thanks -- this is very cool.

**Comment by thenfour** [comment]
Great news! But you're right that when things go wrong, there's little feedback or action to take for users, so I want to keep this issue open.

**Comment by thenfour** [comment]
closing this because the site has changed so much, the topic shall be re-thought. we now have a lot better visual feedback, auto MIDI config, etc, though usability problems still exist!
